exclude: '^ui/node_modules/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^ui/node_modules/
      - id: check-yaml
        exclude: ^ui/node_modules/
      - id: end-of-file-fixer
        exclude: ^ui/node_modules/
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^ui/node_modules/
      - id: trailing-whitespace
        exclude: ^ui/node_modules/
      - id: check-merge-conflict
        exclude: ^ui/node_modules/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        exclude: ^ui/node_modules/
      - id: terraform_tflint
        exclude: ^ui/node_modules/
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide providers
          - --args=--sort-by required
        exclude: ^ui/node_modules/
      - id: terraform_validate
        args:
          - --tf-init-args=-reconfigure
          - --hook-config=--retry-once-with-cleanup=true
        exclude: ^ui/node_modules/
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--framework=terraform
          - --args=--download-external-modules true
          - --args=--soft-fail
          - --args=--skip-check CKV_TF_1 # Disabled to specify the version number as the source of the module, not the commit
          - --args=--skip-check CKV2_AZURE_31 # Disabled because the current module version doesn't support Network Security Group assignement
        exclude: ^ui/node_modules/

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: ^ui/node_modules/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: ^ui/node_modules/

  # Temporarily disabled due to issues with node_modules
  # - repo: https://codeberg.org/frnmst/md-toc
  #   rev: 8.2.3
  #   hooks:
  #     - id: md-toc
  #       args: ['-p', 'github']
  #       exclude: '^ui/node_modules/.*$'
  #       files: '^(?!ui/node_modules/).*\.md$'
