
# Key; must be unique in a given SonarQube instance
sonar.projectKey=bayer-int_af_agentcell_004_95ced983-b965-4caf-88ce-3dd60b2827a5

# (optional) Project name; default: project key
sonar.projectName=af_agentcell_004

# (optional) Version; default: "not provided"
#sonar.projectVersion=1.0

# (optional) Path to source code; relative to the sonar-project.properties file. default: "."
#sonar.sources=.

# (optional ) Encoding of the source code; Default: default system encoding
#sonar.sourceEncoding=UTF-8
